name: Update Cask version

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GITHUB_TOKEN=$GITHUB_TOKEN
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get latest release version from GitHub API
        id: get_version
        run: |
          changed=false
          update() {
            local repover=$(curl -s https://api.github.com/repos/$1/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d '"' -f4)
            local caskver=$(cat $2 | grep "version\s" | cut -d "'" -f2)

            if [[ repover != caskver ]]; then
              changed=true
              sed -i "s/version .*/version '$repover'/g" $2
              git add $2
            fi
          }

          update "Rimsort/Rimsort" "Casks/rimsort.rb"
          update "yaagl/yet-another-anime-game-launcher" "Casks/yaagl-hsr.rb"
          update "loopwork-ai/iMCP" "Casks/imcp.rb"
      - name: Commit and push changes
        run: |
          if [ changed ]; then
            git commit -m "Update casks."
            git push
          fi
