name: Update Cask version

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GITHUB_TOKEN=$GITHUB_TOKEN
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get latest release version from GitHub API
        id: get_version
        run: |
          update() {
            local repo_ver=$(curl -s https://api.github.com/repos/$1/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d '"' -f4)
            local caskfile="Casks/$2.rb"
            local cask_ver=$(cat $caskfile | grep "version\s" | cut -d "'" -f2)

            if [[ repo_ver != cask_ver ]]; then
              sed -i "s/version .*/version '$repo_ver'/g" $caskfile
              git add $caskfile
            fi
          }

          update "Rimsort/Rimsort" "rimsort"
          update "yaagl/yet-another-anime-game-launcher" "yaagl-hsr"
          update "loopwork/iMCP" "imcp"
      - name: Commit and push changes
        run: |
          if ! git diff --cached --quiet; then
            git commit -m "Update casks."
            git push
          fi
